### ISSUE TITLE
An evaluation of '((10) . 20) should output ((10) . 20)

### ISSUE THREAD

**Issue by kariya-mitsuru** [mattn/cisp#18]
In the current implementation, An evaluation of `'((10) . 20)` outputs `((10 . 20) . 10)`.
Additionally, An evaluation of `(cdr '((10) . 20))` outputs `(cdr '((10 . 20) . 10) . ((10 . 20) . 10))`.

I do not understand why they occur, but the current implementation is quite different from common implementations in that a cons cell keeps an atom (like int or string etc.) and a car (or a cdr) simultaneously.

**Comment by mattn** [comment]
Currently, working at fix-cons branch.

https://github.com/mattn/cisp/tree/fix-cons

**Comment by kariya-mitsuru** [comment]
Another example, `(cdr '((10 . 20) (30 . 40)))` should output `((30 . 40))`, but the current implementation outputs `30`.

Should I file a new issue ?

**Comment by mattn** [comment]
Yes, but fixed.
