### ISSUE TITLE
REPL cannot be ended by EOF char(Ctrl-D)

### ISSUE THREAD

**Issue by kariya-mitsuru** [mattn/cisp#32]
In my environment (Ubuntu), REPL cannot be ended by EOF char(Ctrl-D).
In the current implementation, REPL is like below.

```
  while (!s_eof(s)) {
    if (isatty(fileno(stdin))) printf("> ");

    skip_white(s);
    if (s_eof(s)) break;
    ...
  }
```

`s_eof` simply calls `feof`. But `feof` cannot signal `EOF` until next char is read.

**Comment by mattn** [comment]
how about this ? https://github.com/mattn/cisp/commit/bf42d666e24cbd25739db9d6cd8f3f4faf0e31a8

**Comment by kariya-mitsuru** [comment]
Worked correctly if Ctrl-D is a first input after prompt.
But `s_peek`(and `file_peek` etc.) returns `char`, so I think that it should be changed too.
(The type `char` cannot represent the `EOF`. And I think `== -1` is better to be changed to `== EOF`.)

FYI, if you want to care the corner cases, `' '`(spaces) + Ctrl-D needs one more Ctrl-D to end, and `'abc'`(identifier etc.) + Ctrl-D needs two more Ctrl-D to end.
(I think it is not really matter.)

**Comment by mattn** [comment]
> But s_peek(and file_peek etc.) returns char, so I think that it should be changed too.

It's same as `cat`. If typing some characters into the prompt and CTRL-D after the typing some, you can see the letters you typed on the screen.

**Comment by mattn** [comment]
Do this change fixes your issue?

``` diff
diff --git a/cisp.c b/cisp.c
index 5d598e4..1e072d1 100644
--- a/cisp.c
+++ b/cisp.c
@@ -160,9 +160,9 @@ dump_node(NODE *node) {
   puts(buf);
 }

-static void
+static int
 skip_white(SCANNER *s) {
-  int c;
+  int c = 0;
   while (!s_eof(s)) {
     c = s_peek(s);
     if (c == -1) break;
@@ -172,6 +172,7 @@ skip_white(SCANNER *s) {
       while (!s_eof(s) && s_peek(s) != '\n') s_getc(s);
     } else break;
   }
+  return c;
 }

 static NODE*
@@ -263,8 +264,9 @@ static NODE*
 parse_paren(SCANNER *s) {
   NODE *head, *node, *x;

-  skip_white(s);
-  if (s_eof(s)) return raise(s, "unexpected end of file");
+  if (skip_white(s) == -1 || !s_eof(s)) {
+    return raise(s, "unexpected end of file");
+  }

   head = node = new_node();
   node->t = NODE_CELL;
@@ -279,7 +281,6 @@ parse_paren(SCANNER *s) {
       }
       free_node(child);

-      skip_white(s);
       child = parse_any(s);
       if (child == NULL) return NULL;
       node->cdr = child;
@@ -412,7 +413,9 @@ parse_any(SCANNER *s) {
   NODE *x = NULL;
   char c;

-  skip_white(s);
+  if (skip_white(s) == -1 || !s_eof(s)) {
+     return raise(s, "unexpected end of file");
+  }
   if (s_eof(s)) return raise(s, "unexpected end of file");

   if (s_peek(s) == '(') {
@@ -2194,8 +2197,7 @@ load_lisp(ENV *env, const char *fname) {
     return e;
   }

-  skip_white(s);
-  if (!s_eof(s)) {
+  if (skip_white(s) == -1 || !s_eof(s)) {
     free_node(top);
     fclose(fp);
     return invalid_token(s);
@@ -2422,8 +2424,9 @@ main(int argc, char* argv[]) {
   while (!s_eof(s)) {
     if (isatty(fileno(stdin))) printf("> ");

-    skip_white(s);
-    if (s_eof(s)) break;
+    if (skip_white(s) == -1 || !s_eof(s)) {
+      break;
+    }

     node = parse_any(s);
     if (node == NULL) {
```

**Comment by mattn** [comment]
Ah, sorry. This change break all.

**Comment by kariya-mitsuru** [comment]
I am afraid that my comment above is confused you.
There is no relation between the `s_peek`'s return type and `' '`(spaces) or `'abc'`(identifier etc.) + Ctrl-D needs more than one Ctrl-D to end.

The number of Ctrl-D doesn't matter, I think either is okay.
But I think the `s_peek`'s return type should not be `char`.

When `s_peek` is encountered eof, it must return eof sign differed from all characters that can be represented as `char` because `s_peek` may return any character if it is not encountered eof.
So, `s_peek` must be able to return all `char` value (in general, `0` to `255`), and the other value that represents eof sign.

**Comment by mattn** [comment]
should be fixed.
