### ISSUE TITLE
a nested defun'ed function cannot be called.

### ISSUE THREAD

**Issue by kariya-mitsuru** [mattn/cisp#33]
In current cisp's implementation, a nested `defun`'ed function like the `y` below cannot be called.

```
(defun x (x) (defun y (y) (print (* x y))) (print x) (y x))
(x 10) ; <- cisp: illegal function call: y
(y 20) ; <- cisp: illegal function call: y
```

In the common lisp, `defun` always defines a global function even if it is nested other `defun`.

```
(defun x (x) (defun y (y) (print (* x y))) (print x) (y x))
(x 10) ; <- outputs 10 and 100
(y 20) ; <- outputs 200
```

On the other hand, the scheme's equivalent `define` defines a function in the current environment.

```
(define (x x1) (define (y y1) (print (* x1 y1))) (print x1) (y x1))
(x 10) ; <- outputs 10 and 100
(y 20) ; <- undefined function y
```

The common lisp has another construct `labels` for defining local functions.

```
(defun x (x) (labels ((y (y) (print (* x y)))) (print x) (y x)))
(x 10) ; <- outputs 10 and 100
(y 20) ; <- undefined function y
```

I think that the cisp should choice either behavior.
(I like the scheme's behavior but the common lisp's behavior may be more consistent because cisp is LISP-2.)

**Comment by kariya-mitsuru** [comment]
Sorry, the common lisp has another construct `flet` for defining local functions. (I didn't know.)
A difference between `labels` and `flet` are similar to a difference between `let` and `let*`.

```
(setq x 1)
(let  ((x 2) (y x)) (print y)) ; -> outputs 1 because (y x) refers global x
(let* ((x 2) (y x)) (print y)) ; -> outputs 2 because (y x) refers local x
```

```
(defun x () (print 1))
(flet   ((x () (print 2)) (y () (x))) (y)) ; -> outputs 1 because (y () (x)) refers global x
(labels ((x () (print 2)) (y () (x))) (y)) ; -> outputs 2 because (y () (x)) refers local x
```

Note that `flet` cannot define recursive functions (include mutual recursive functions) because the local function cannot refer itself.

**Comment by kariya-mitsuru** [comment]
Of course, it makes sense perfectly that cisp's `let` has the behavior of the common lisp's 'let*`, etc. :-)

**Comment by mattn** [comment]
あまり理解してないのですが、この件最初の x y の y は 200 になるべきというのは変わらずなんでしょうか？

**Comment by kariya-mitsuru** [comment]
common lisp の場合はそうですね。
`(defun y (y) (print (* x y)))` が評価される際、つまり関数 `x` が実行される際には、関数 `x` の環境内で評価が行われるので、その中の変数としての `x` は関数 `x` の仮引数を指します。
また、変数 `y` は当然定義される関数 `y` の仮引数を指します。
しかし、`defun` で定義される関数 `y` 自体は、グローバルな環境で束縛されます。
common lisp はこのあたりの動きが（このあたりの動きも、かな）気持ち悪いんですよね…（個人の感想です）
scheme の動きはシンプルなんですけど…（個人の感想です）

**Comment by mattn** [comment]
この件の修正は一度やってみて直ったのですが

https://github.com/mattn/cisp/commit/2d1ca607cf87a3f9d74000318c254cf84effc488

今度は setq のテストがNGになってしまいました。
