### ISSUE TITLE
(eval (cons '+ (cons 1 (cons 2 nil)))) should be evaluated to 3

### ISSUE THREAD

**Issue by kariya-mitsuru** [mattn/cisp#35]
In the current implementation, `(eval (cons '+ (cons 1 (cons 2 nil))))` is evaluated to `(+ 1 2)` but I think it should be evaluated to `3`.

`(cons '+ (cons 1 (cons 2 nil)))` is evaluated to `(+ 1 2)`, so I think that `(eval (cons '+ (cons 1 (cons 2 nil))))` should be equivalent to `(eval '(+ 1 2))`, that is `3`.

**Comment by kariya-mitsuru** [comment]
Hmm, I think that it is still evaluated to `(+ 1 2)`.

**Comment by mattn** [comment]
Ah, sorry. fixed.
